// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import { defineConfig } from 'prisma/config';
import { urlAdministrativa } from './src/config/url-banco';

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
  },
  datasource: {
    // A escolha da conexão (e o porquê de string vazia contar como ausente)
    // está documentada em `src/config/url-banco.ts`.
    url: urlAdministrativa(),
  },
});
